### PR TITLE
Switch to debian stretch

### LINKED ISSUE #4: target multiple architectures
Our maintainers are all now using M1 macbooks and have found that this image currently does not work with ARM architectures. We could republish supporting multiple architectures by following a guide similar to [this one](https://dev.to/tidalmigrations/multi-cpu-architecture-container-images-how-to-build-and-push-them-on-docker-hub-or-any-other-registry-2981). 

I tried doing so and ended up publishing https://hub.docker.com/r/travi/docker-gitbox (after resolving an issue through https://github.com/semantic-release/docker-gitbox/pull/3) with the intent of re-publishing again under the semantic-release org, but it still fails. It does overcome the architecture limitation, but results in a different error that does not happen when running on x86. So, probably still related to architecture somehow, but unsure why so far. 

the new error is as follows:
```
/etc/init.d/fcgiwrap start
[FAIL] Starting FastCGI wrapper: fcgiwrap failed!
```

my docker knowledge is super rusty but i didnt find additional information about the error in logs from the container or other details to point to a good next step.

### PR DESCRIPTION
**Pull request by jsoref**
With this, I'm able to run the generated image on my m1 and it seems to do what I'd expect...

This probably closes #4

### CODE REVIEW

**Comment by fgreinacher** [comment]
~~This LGTM - we could also skip `stretch` and move to `buster` but both will be supported for a [long time](https://wiki.debian.org/LTS).~~ Sorry, I just noticed that actually `stretch` is out-of-support, so we might want to switch to `bullseye` (aka `stable`) @jsoref.

@travi

**Comment by travi** [comment]
> Sorry, I just noticed that actually `stretch` is out-of-support, so we might want to switch to `bullseye` (aka `stable`)

considering that `jessie` is also EOL, i'm not completely against smaller steps. we certainly want to get updated to a supported version in the end, but i'm ok with iterating to get there. working is better than not working.

if it is simple to move to `bullseye`, i'm obviously fine with that, but if smaller steps make it less risky for the effort to inflate significantly, i think there is value to getting to working first. once we get to a working state, i'd like to get a github action set up to publish to image versions to our semantic-release docker hub account, which would simplify the further iterations for getting the remainder up to date. 

seem reasonable?

**Comment by travi** [comment]
i published a multi-architecture build of this to https://hub.docker.com/repository/docker/travi/docker-gitbox under the `stretch` tag and updated https://github.com/semantic-release/semantic-release/blob/846f4c23b92add5254e53f819b51bb2be08438ea/test/helpers/gitbox.js#L6 to reference it. i havent looked too far into it, but the integration tests still time out. from what i can tell from the docker desktop dashboard, it does seem to be running ok, at least.

**Comment by jsoref** [comment]
I'd encourage you to merge this as is, and then we can merge an additional commit that switches to bullseye.

The bullseye move will be similar (bumping to an even newer php), but I think it's better to show the incremental changes.

**Comment by travi** [comment]
> the integration tests still time out

i added some simple log statements to the test flow and confirmed that gitbox (this image) and the npm registry complete their startup, but the promise for starting the mockserver does not seem to be resolving.

this highlights why i agree that we should approach this iteratively. there are likely several pieces that will need to come together to get us back to working. i dont want to invest more effort than necessary in confirming that there is at least a workable path forward, in case we need to abandon any of the existing parts for alternative paths.

**Comment by travi** [comment]
i captured https://github.com/semantic-release/docker-gitbox/issues/7 for a follow-up upgrade to `bullseye`, but i think it makes sense to merge this step at this point.

thank you so much for the contribution @jsoref!!

**Pull request merged**
